
function agc_config(this_block)

  % Revision History:
  %
  %   21-Jun-2021  (09:25 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\vovan\Desktop\paper\agc.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('agc');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('reset');
  this_block.addSimulinkInport('enable');
  this_block.addSimulinkInport('data_in_i');
  this_block.addSimulinkInport('data_in_q');

  this_block.addSimulinkOutport('data_out_i');
  this_block.addSimulinkOutport('data_out_q');
  this_block.addSimulinkOutport('agc_gain');

  data_out_i_port = this_block.port('data_out_i');
  data_out_i_port.setType('Fix_12_9');
  data_out_q_port = this_block.port('data_out_q');
  data_out_q_port.setType('Fix_12_9');
  agc_gain_port = this_block.port('agc_gain');
  agc_gain_port.setType('UFix_12_10');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('reset').width ~= 1);
      this_block.setError('Input data type for port "reset" must have width=1.');
    end

    this_block.port('reset').useHDLVector(false);

    if (this_block.port('enable').width ~= 1);
      this_block.setError('Input data type for port "enable" must have width=1.');
    end

    this_block.port('enable').useHDLVector(false);

    if (this_block.port('data_in_i').width ~= 12);
      this_block.setError('Input data type for port "data_in_i" must have width=12.');
    end

    if (this_block.port('data_in_q').width ~= 12);
      this_block.setError('Input data type for port "data_in_q" must have width=12.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('agc.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

